### ISSUE TITLE
Error 'The input file has failed to upload or you have not selected a file to upload'

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#1]
Hello,

I've just discovered this extension/module which looks like it could help my situation greatly (as CSVGrab doesn't allow updating, only new imports).

I've installed the extension and module, but haven't yet been able to upload any CSV. I'm running EE1.7 Build 20101018 and have tried this with all other extensions disabled (Category Checkboxes and Mark Huot's 'File') but just cannot seem to fathom it.

Any assistance greatly appreciated!
Justin

**Comment by designbyfront** [comment]
Hi Justin,

Thanks for your query.
Apologies, it appears that GitHub has removed the empty upload directory from the repository. I have re-added this directory to the repository.

Within `/system/modules/import_data/files/` there should be a directory `upload_input_files` with full permissions (777). It may be easiest for you to simply add this manually yourself.
Can you retry after confirming that the upload directory is in place with the correct permissions?

Regards,
Alistair

**Comment by judin** [comment]
Hi Alistair,

Thank you very much for your assistance. I've been able to successfully import most of the fields I require, including basic categories.

One thing I do wonder is if the status (Open, Closed etc) gets overwritten, as it does seem to in my instance if I leave the field blank (eg not importing this data).

Also, I haven't got the relationship field to work yet. I've been using the Title, but can't get it to work using this. Have you any thoughts on how this works, as I didn't find the readme very helpful where this is concerned.

Kind regards,
Justin

**Comment by judin** [comment]
Alistair,

Could it be because the relationship is a field in the same weblog?

**Comment by designbyfront** [comment]
Hi Justin,

Many apologies for the delay; it's been a bit hectic recently. I now have some time available and can assist if you still wish.

You are correct, the status was only preserved when provided with a value. This condition has now been removed and so statuses should always be preserved if they exist. Please check out the latest version from the repository.

Regarding the relationship field, I will try to describe the process below. Any comments you could give me on improving the readme would be appreciated.
- In stage one, tick the "_Relationships with existing entries?_".
- Stage two will now provide you with the ability to map the relationship. That is, you can select which column of the input file is a "relationship" to existing data in the system.<br />
  Say you have a weblog "countries" with names of countries. You now import businesses to the weblog "businesses" which has the field "location" which is a relationship field to the "title" field in "countries" weblog. The column in the input file which contains the businesses location  (the "**Input data field**") "_has a relationship with_" the "countries" weblog ("**Section**") and the "title" field ("**Field**").
- Now in stage three you assign the column containing the businesses locations to the "location" field, and when imported, the module will look up the corresponding entry id by looking in the "countries" weblog for an entry where the "title" field is the same as the imported field.

I have just read your last message "_Could it be because the relationship is a field in the same weblog?_". This should not be a problem, so long as the entry with which the relationship is being made exists.

The test I tried was to create a weblog with one field: a relationship field to itself on the "title" field.

```
Title,Relationship
"I am the first","I am the second"
"I am the second","I am the first"
```

When imported, the "I am the first" entry has no relationship, as at that time the "I am the second" entry did not exist. However, the "I am the second" entry has a relationship to "I am the first", as this first entry existed when the second entry was created.

Could you be trying to create relationships to entries which do not yet exist?
Simply importing the file again and making use of the "_Unique?_" checkbox will cause the module to update the entries (rather than create new ones). As all necessary entries exist, the relationships will be added.

I hope that helps. Please come back to me if you have any questions or if issues are still occuring with the use of the relationship field. Details to provide would be the weblogs you are using and the data being input.

Regards,
Alistair
