### ISSUE TITLE
Text does not keep default text formatting

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#2]
Hi guys,

Sorry for the delay in responding to the previous email. It's been all hands on deck here the last few weeks!

I've just found that, when importing to a text field, the default text formatting is not being followed. In this instance, I'm importing into a format 'none' field, but it's adding <p> </p> tags around the content.

I'll post issues in individual fields so you can look at if/when you have time.

Thanks,
Justin

**Comment by designbyfront** [comment]
Hi Justin,

No worries, I know the feeling.

Thank you for pointing this out - it was a bug!
The field formatting was not being passed to EE, which was defaulting to 'XHTML'.

I have updated the repository with this fix.
I've also made some other fixes and feature changes over the last few days. For the most up to date version, just grab the latest release.
If you don't want them and just want the fix for this issue, you can see the changes I made here: designbyfront/Import-Data-into-ExpressionEngine@c5d03185d93edc0ae65885653d14616da78ad204

Let me know if you run into any more issues!

Regards,
Alistair

**Comment by judin** [comment]
Thanks very much for this - downloaded and installed the new version and it _seems_ to be working. I'll be testing this further over the next few days.

Any update on delimited categories...? :-)

Thanks for your help,
Justin

**Comment by judin** [comment]
Wait...! What is this I see by Category... 'in field delimiter'? Gonna try this now!

**Comment by designbyfront** [comment]
Hi Justin,

That's Good to know! As I said, let me know if you run into any issues.

"_Any update on delimited categories...?_" - just as I finish work on it today! :)

The "_in field delimiter_" means that you can input data which has an internal delimiter - 
Say your input is "1|2|3|4", and you specified '|' as the delimiter, this would be the equivalent of "1","2","3","4"
The _multiselect_ and _in field delimiter_ should work in combination, so you could select two fields with input "1|2|3|4" and "5|6|7|8"  and this would be the equivalent of "1","2","3","4","5","6","7","8"
Currently is is supported by the categories field and playa fields.

Let me know if you have any thoughts.

Regards,
Alistair

**Comment by judin** [comment]
The import of categories seemed to work perfectly. One thought, it seems to overwrite categories if you import 'other' categories. Is this the case? Would it be possible to be additive by default?

Possibly, is there a way to select an import clear all categories? Just thinking around the benefits of both.

Also, have you thought whether you may get this supporting automated (CRON-based, most likely) importing, in the first instance by locating a file within a given folder on the server, ala DataGrab for EE2?

**Comment by judin** [comment]
One other - is it possible to import without a Title field being given? A good example is if this was being used to update data rather than import from scratch, as the unique option would allow you to use another field to identify the title?

Still haven't got relationships working - will give it another go and get back to you with any comments!

Thanks for your help, Alistair.

**Comment by designbyfront** [comment]
Hi Justin,

"**It seems to overwrite categories if you import 'other' categories.**"
- "**Is this the case?**"  
  By 'other' do you mean supplying new categories when updating from an import? If so, then yes, this is the case.  
  Addition occurs within each import, but once a new import starts, it will overwrite the existing categories with those assigned. This means that if you wanted to change the category of an entry, you would simply give it the new categories and it would remove the existing ones for you.
- "**Would it be possible to be additive?**"  
  This is possible to do. Perhaps some sort of setting detailing the behaviour. I will look into this for you. 

"**Is there a way to select an import clear all categories?**"  
Yes, when importing just map an empty input field to categories. As discussed above, it's not additive and so will overwrite the existing categories with nothing.

"**supporting automated (CRON-based, most likely) importing**"  
Yes, this is something that is on my todo list - it will involve importing and exporting settings. I will bump it up the list and try to get to it sooner.

"**Is it possible to import without a Title field being given?**"  
An entry must have a title. However, if that entry exists, the module will take the existing title. So yes, is you are updating an existing entry you only need a unique field.  
I had not thought to test this scenario, but it does work. The module throws two warnings due to undefined indexes - I have now added checks to remove these warnings and just updated the repository.

"**Still haven't got relationships working**"  
Let me know if you have problems with it :)

Hope that helps. Let me know if there's anything else. I'll have a look into the additive issue.

Regards,
Alistair

**Comment by judin** [comment]
Regarding Categories being 'additive'.

For example, I've manually added some categories to entries but have now thought of a new category I'd like to apply to a number of entries. I can't do this easily with the import, as it will overwrite my categories and only use the new one.

I'm going to work at importing a small number of 'relationship' entries, to see if I can get this working in the next few days.

Thanks,
Justin

**Comment by designbyfront** [comment]
Hi Justin,

I have added in the additive functionality.
There is now a checkbox "_Disable overwrite behaviour_" beside the categories field and playa fields which, when checked, should allow addition to that field.

Let me know if you run into any issues.

Regards,
Alistair
