### ISSUE TITLE
TXT input file type

### ISSUE THREAD

**Issue by judin** [designbyfront/Import-Data-into-ExpressionEngine#7]
Hi Alistair,

I've just been reading up and trying to implement TSV (tabbed separated values), as you describe in the Wiki - https://github.com/designbyfront/Import-Data-into-ExpressionEngine/wiki/Read-Me-Advanced#interestinginputtype

Am I doing something wrong, or is there a step missing perhaps? I've completed this literally as it states.

Thanks,
Justin

**Comment by designbyfront** [comment]
Hi Justin,

Are you using the most up to date version?
Unfortunately when the code was restructured, it has made the TSV code in the wiki incorrect; you can not longer pass custom variables to the class constructors.

When restructuring the code, it was decided to make it easier to add new input types. All you now need to do it add your input type to the "_import_data/files/input_types/_" directory and then add the type to  the _$input_types_ variable (input type class name => readable name) in "_import_data/mcp.import_data.php_"

So, in order to make the TSV type:
- Make a copy of the CSV input type file
  ("_import_data/files/input_types/Csv_file.class.php_")
- Rename the class name (_class Csv_file_) and PHP4 constructor (_function Csv_file_) to **Tsv_file** 
- Set the delimiter parameter of both constructors from $delimiter=',' to **$delimiter="\t"** (there should be three places to change this).
- In "_import_data/mcp.import_data.php_" add your new type to the _$input_types_ variable: **'Tsv_file' => 'TSV',**

If you have any other questions, just let me know.

Regards,
Alistair

**Comment by judin** [comment]
So I've got TSV working (using delimiter "\t"). Still got problems with category import so am going to strip out my database data as I said and test.

Cheers
